[package]
name = "tetris"
version = "0.1.0"
authors = ["Tanner Evins <tanner@tannerevins.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
rand = "0.7.2"
nalgebra = "0.18.1"
